name = "demos"
description = "Demo for Ollama API library"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["demos"]

[[depends-on]]
ollama_api = "*"

[build-profiles]
"ollama_api" = "development"

[[pins]]
ollama_api = { path='..' }
